name: Travelling Salesman - Group 21

on:
  push: 
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        pip-installs: ["pip --upgrade", "torch"]
    
    steps:
      # getting git code base
      - uses: actions/checkout@v4

      # Installing python Environment
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Installing project Dependencies
      - name: Installing Dependencies
        run: python -m pip install ${{ matrix.pip-installs }}

      # Running Code
      - name: Running code
        run: python main.py
    
    
  
  
