name: Travelling Salesman - Group 21

on:
  push: 
    branches: ["main", "dev"]
    

jobs:
  build:
    strategy:
      matrix:
        os-version: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os-version }}
        
    steps:
      # getting git code base
      - uses: actions/checkout@v4

      # Installing python Environment
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Installing project pip
      - name: Installing Pip
        run: python -m pip install pip --upgrade

      #Installing Dependiencies
      - name: Installing Program Dependencies
        run: python -m pip install -r requirements.txt

      # Running Code
      - name: Running code
        run: python main.py
    
    
  
  
